plugins:
    aws_get_vpn_connection_info:
        executor: central_deployment_agent
        install: false
        source: https://github.com/tomahkvt/aws-get-vpn-connection-info/archive/1.0.zip
        package_name: aws-get-vpn-connection-info
        package_version: '1.0'

node_types:
  cloudify.aws.nodes.VPNConnection:
    derived_from: cloudify.nodes.Root
    interfaces:
      cloudify.interfaces.lifecycle:
        start:
          implementation: aws-get-vpn-connection-info.plugin.tasks.start
          inputs: {}
