plugins:
    aws-get-vpn-connection-info:
        executor: central_deployment_agent
        install: false
        source: https://github.com/tomahkvt/aws-get-vpn-connection-info/raw/master/aws-get-vpn-connection-info.zip
        package_name: aws-get-vpn-connection-info
        package_version: '1.0'

node_types:
  cloudify.aws_get_vpn_connection_info.nodes.VPNConnection:
    derived_from: cloudify.nodes.Root
    interfaces:
      cloudify.interfaces.lifecycle:
        start:
          implementation: aws-get-vpn-connection-info.plugin.tasks.start
          inputs: {}
